### PR TITLE
Add a README.md

### PR DESCRIPTION
**Pull request by kalleth**

### CODE REVIEW

**Comment by evilstreak** [comment]
Looks good. One thing: the README is inconsistent with its used of `webop`, `web_ops` and `web ops`. It would be good to make all of those consistent.

**Comment by kalleth** [comment]
@evilstreak I've updated the usage of describing people who have a `web ops` speciality to read `web operations`. The discrepancy between `webops` and `web_ops` is because the code sets the `rota_skill_group` of each person to `"webops"` but the method defined on a `RotaWeek` is `web_ops`, hence the inconsistency is nasty but describes the current implementation.

i'll modify this in a separate branch and add a separate PR to keep the documentation in sync with the code.

**Comment by evilstreak** [comment]
:+1:

**Comment by kalleth** [comment]
@evilstreak Happy for you to merge this if you're happy -- doesn't really require any more review than you've just given it :)

**Comment by evilstreak** [comment]
I would, but I can't. Permissions!

**Pull request merged**
